### ISSUE TITLE
The conflict of interest policy is not publicly available

### ISSUE THREAD

**Issue by adarsh** [rubytogether/feedback#1]
Perhaps it could be added to [the FAQ](https://rubytogether.org/companies#faq)?

@indirect - can you point me to the policy text or summary so I can add it?

Background:
[![image](https://user-images.githubusercontent.com/913757/35707891-70702abc-0760-11e8-8439-aee87ed05672.png)](https://twitter.com/amcaplan/status/959172854850957313
)

**Comment by indirect** [comment]
That's a great idea. The conflict of interest policy is currently languishing inside a PDF of the corporate bylaws, but should definitely be available to anyone who is interested.

**Comment by adarsh** [comment]
The conflict of interest section is attached here as a PDF. I'll open an issue on the RT site to get it linked there as well.
[Ruby Together Conflict of Interest Policy.pdf](https://github.com/rubytogether/feedback/files/1696169/Ruby.Together.Conflict.of.Interest.Policy.pdf)

**Comment by adarsh** [comment]
CC @amcaplan
